remote:
  method: release
  keepReleases: 5
  path: /var/www/nimbly.io

code:
  scm: git
  repo: git@gitlab.com:nimbly/nimbly.git
  branch: master
  username: ~
  password: ~

authentication:
  username: fedora
  password: ~
  key: /home/brent/.ssh/scootlist.pem
  passphrase: null

environments:

  production:
    servers:
      - host: nimbly.io
        migrate: true

  staging:
    remote:
      method: update
      path: /var/www/staging.nimbly.io

    servers:
      - host: nimbly.io
        migrate: true
